[build]
command = "npm run build"
functions = "netlify/functions/"
publish = "build/"

[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 9000
